### ISSUE TITLE
Tambahkan Fitur Back

### ISSUE THREAD

**Issue by AkiraRen07** [billalxcode/pintarnet#11]
Agar lebih Memudahkan user dalam menggunakan aplikasi ini, lebih spesifiknya untuk pengguna android fitur ini akan membantu

**Comment by billalxcode** [comment]
![image](https://github.com/billalxcode/stemdja-master-app/assets/71764176/c18ee6fe-b14e-4d1c-8ba1-26a0340c5bc9)

Beress
