### ISSUE TITLE
tidak bisa tambah data saat mode mobile

### ISSUE THREAD

**Issue by malikmaulana03** [billalxcode/pintarnet#12]
![Screenshot (5)](https://github.com/billalxcode/stemdja-master-app/assets/132648270/16b047f8-4683-444c-b425-f9d560e46eab)

Mohon Diperbaiki Puhh
saat memasuki mode mobile tombol tambah data tidak bisa ditekan dengan kata lain tidak bisa menambahakan data

**Comment by billalxcode** [comment]
Done #14
